### ISSUE TITLE
Turn off caching 

### ISSUE THREAD

**Issue by sameronline** [wodby/drupal-nginx#10]
Is there is away to easily turn off caching completely? for example when there is css or js file is updated. i have to always use ctrl + f5 to pick the new files or resources.

**Comment by sameronline** [comment]
From what i read seems like https://www.nginx.com/blog/nginx-caching-guide/ "sendfile" parameter should be off?

**Comment by csandanov** [comment]
With revamped image you can now disable caching, see env vars

**Comment by sameronline** [comment]
@csandanov  yeah all good now.. thanks, you may close this now
