### ISSUE TITLE
502 Bad Gateway on some Drupal pages due to buffers too small

### ISSUE THREAD

**Issue by tanc** [wodby/drupal-nginx#11]
I'm finding some Drupal pages give me a 502 error which I can resolve by increasing nginx fastcgi_buffers to:

```
fastcgi_buffers 8 16k;
fastcgi_buffer_size 32k;
```

**Comment by pprishchepa** [comment]
Which buffer size will fit you requirements?

**Comment by tanc** [comment]
The two lines I posted above works for me

**Comment by tanc** [comment]
This keeps biting me on most sites, any chance of getting it in?

**Comment by larowlan** [comment]
+1 - affecting me too

**Comment by csandanov** [comment]
The new drupal-nginx image is now based on [wodby/nginx](https://github.com/wodby/nginx) which now has these settings as you suggested (see [README](https://github.com/wodby/nginx/blob/master/README.md) to see all default settings).

**Comment by rachidbigm** [comment]
same here !
