### ISSUE TITLE
nginx_1  | nginx: [emerg] no port in upstream "backend" in /etc/nginx/conf.d/drupal.conf:22

### ISSUE THREAD

**Issue by james-gonzalez** [wodby/drupal-nginx#18]
Just started happening today, in the last few hours.

`nginx_1  | nginx: [emerg] no port in upstream "backend" in /etc/nginx/conf.d/drupal.conf:22`

When we startup our nginx instance.

**Comment by csandanov** [comment]
There was a bug in yesterday's build. I've added new tests with Drupal images, now all tests passing, so it should work now, use image tag [DRUPAL VERSION]-1.10.

**Comment by drasgardian** [comment]
Still seeing this issue with 8-1.10

**Comment by csandanov** [comment]
How do you use this image? Do you specify required env var NGINX_BACKEND_HOST to define backend upstream?

**Comment by drasgardian** [comment]
I have the following:

  nginx:
    image: wodby/drupal-nginx:8-1.10
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"

**Comment by csandanov** [comment]
You're using the new version of drupal-nginx image which requires different env vars and incompatible with docker4drupal 1.x. Please use wodby/drupal-nginx:1.10-1.1.0 recommended in d4d compose file. The new image will be used for d4d 2.0 (not released yet)

**Comment by drasgardian** [comment]
Thanks, I have it working ok with wodby/drupal-nginx:1.10 now. Looking forward to d4d 2.0.
