### ISSUE TITLE
Drush 8.1.10 is not compatible with Drupal 7

### ISSUE THREAD

**Issue by jurgenhaas** [wodby/drupal-nginx#21]
This is reported several times in the Drush issue queue (e.g. https://github.com/drush-ops/drush/issues/2415) and it would be great if the drupal-nginx image for Drupal 7 could come with Drush 8.1.4

**Comment by csandanov** [comment]
It should have been an issue for https://github.com/wodby/drupal-php, I think the latest versions of 7.1/7.0/5.6 (not tagged) come with drush 8.1.10

**Comment by jurgenhaas** [comment]
That's true, just that drupal-php doesn't have Drupal version specific images. However, this is probably more of a Drush problem and I'll try to get it sorted there.
