### ISSUE TITLE
Problem with Drupal 6 and clean URLs

### ISSUE THREAD

**Issue by jurgenhaas** [wodby/drupal-nginx#22]
Just ran into a problem with the image wodby/drupal-nginx:6-1.10-2.0.0 and clean URLs in a Drupal 6 installation. Regardless of what I put in as the path, I always get the front page being delivered. The logs in nginx and php containers are not showing any errors.

When I put `$conf['clean_url'] = 0;` into my settings.php, then I can properly navigate the site.

I'm not an expert for Nginx and therefore thought I'd better ask here, hoping that there is an easy resolution for this.

**Comment by csandanov** [comment]
Yes, there was a small bug, try latest version wodby/drupal-nginx:6-1.10

**Comment by jurgenhaas** [comment]
I see two tags now: `wodby/drupal-nginx:6-1.10` and `wodby/drupal-nginx:6-1.10-2.0.0`. Your change went into the former one, I'm using the latter one. What's the difference? Can I use the former one?

**Comment by jurgenhaas** [comment]
Looks like the former one is working OK and the bug is fixed. Still, would be good to understand the difference in the versioning here. Thanks for your support @csandanov

**Comment by csandanov** [comment]
2.0.0 is a tag to freeze images for docker4drupal, we run tests to make sure all of the containers used in docker4drupal work well together
