### ISSUE TITLE
Add redirect/map option

### ISSUE THREAD

**Issue by arrubiu** [wodby/drupal-nginx#23]
Hi!
I'm using this image, obviously with docker4-drupal stack, for a migration site from d7 to d8.
I've to implenents some redirect in nginx.
It could be useful to add an option (a file to include with volumes) to add a map file for redirects.

What do you think?

Thanks,
Sergio

**Comment by csandanov** [comment]
Yes, that's a good idea. Added a new env var `NGINX_SERVER_EXTRA_CONF_FILEPATH`, use it to specify path to your extra conf file (e.g. /var/www/html/server.conf, example: https://github.com/wodby/drupal-nginx/blob/master/8/1.10/test/server.conf
