### ISSUE TITLE
Drupal's tests that check cache headers fail

### ISSUE THREAD

**Issue by larowlan** [wodby/drupal-nginx#27]
E.g. see EntityResourceTestBase

https://github.com/wodby/drupal-nginx/blob/master/8/1.13/drupal.conf.tpl#L14 is the issue

**Comment by larowlan** [comment]
Also, content type in fast_cgi_param should add `if_not_empty`

**Comment by csandanov** [comment]
We now keep Drupal headers by default, new env var to hide them https://github.com/wodby/drupal-nginx/commit/efa7c2208c09a8cdbcde259bb8d1c87f382644cc

Not sure I undestand your command about `if_not_empty`. Could you please explain?

**Comment by larowlan** [comment]
At present we always add the Content-Type header, but there are tests in Drupal's rest API that are checking that if no content-type header is present, it returns a 406.

Those fail with d4d because we always add the content type-header.

We need to change the line that sets the content-type header in the nginx conf to add `if_not_empty`.

Thanks again

**Comment by csandanov** [comment]
Thanks for clarifying, I've added the param, try the latest image, e.g. `wodby/drupal-nginx:8-1.13`

**Comment by larowlan** [comment]
You sir are a legend
