### ISSUE TITLE
no port in upstream after restart

### ISSUE THREAD

**Issue by ovidijusr** [wodby/drupal-nginx#28]
everything start fine except nginx dies with code exit 1
and gets this error message
`nginx_1  | nginx: [emerg] no port in upstream "backend" in /etc/nginx/conf.d/drupal.conf:23`

**Comment by rubach** [comment]
I saw this same issue, and it was from `NGINX_BACKEND_HOST` not being defined in my docker-compose.yml file. Once I set that to the PHP docker image that I'm using, it worked. 

Looking at https://github.com/wodby/drupal-nginx/blob/master/8/1.12/test/docker-compose.yml is what tipped me off to the issue.

**Comment by csandanov** [comment]
The error is pretty clear, look up the definition of the backend upstream in your /etc/nginx/nginx.conf. Normally port should be `9000` by default unless you've overridden it with `NGINX_BACKEND_PORT`.

**Comment by ovidijusr** [comment]
Thank you for trying to help me out.
I am newbie on docker so don't really know how it actually works.
The thing is it was working for like a month and after i shut down my mac it stopped working (and getting that error message from nginx) 

after adding nginx backend host line I get this message  `nginx_1  | nginx: [emerg] host not found in upstream "drupal:9000" in /etc/nginx/nginx.conf:63`

My docker-composer file.yml

`version: "2"

services:
  db:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6.
    environment:
      PHP_SITE_NAME: docker-dev
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: drupal # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_BACKEND_HOST: drupal
      NGINX_DOCROOT: drupal # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 3G
      PHP_MAX_INPUT_VARS: 3G
    ports:
     - "8001:80"`

Thanks again :)

**Comment by csandanov** [comment]
You have an outdated compose file with old environment variables. Because you're using non-tagged docker images they were updated but the compose file remained old. See latest docker-compose.yml from docker4drupal repository or just start from scratch.

**Comment by ovidijusr** [comment]
thank you very much! it solved my problem
