### ISSUE TITLE
Running into an issue running update.php

### ISSUE THREAD

**Issue by tomfriedhof** [wodby/drupal-nginx#30]
Not sure if anyone else has run into this problem, but I had to update my nginx config location block for update.php to the following:

```
    location ~* ^/update.php {
        include fastcgi_params;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param SCRIPT_NAME /update.php;
        fastcgi_param SCRIPT_FILENAME $document_root/update.php;
        fastcgi_pass backend;
    }
```

Any one else running into to issues running update.php without this?

**Comment by csandanov** [comment]
What is the problem with the original location? What Drupal version?

Normally the param you've specified in the location inherit from the parent context (server).
