### ISSUE TITLE
Option to run Nginx on a different port

### ISSUE THREAD

**Issue by badri** [wodby/drupal-nginx#32]
Hi,
If I'm using varnish, I'd possibly run varnish on port 80 and nginx in a different port.
The current setup does not expose the option to change nginx port. Can this be a possible enhancement? I'd love to contribute this.

**Comment by csandanov** [comment]
You can map container port to any port on the host machine, it's not necessary to change it inside. Besides, usually, you'd need to run another reverse proxy before varnish to terminate SSL.
