### ISSUE TITLE
NGINX_CONF_INCLUDE

### ISSUE THREAD

**Issue by readingdan** [wodby/drupal-nginx#33]
I am trying to use NGINX_CONF_INCLUDE to set a custom nginx config to be used with drupal 6, however it does not seem to be working as expected.

I have copied the file from /etc/nginx/conf.d to my docroot and created an alias in my docker-compose.yml file e.g.

NGINX_CONF_INCLUDE: /var/www/html/d6_nginx.conf

After restarting the container, it does not seem to be picking up on my replacement file.

**Comment by csandanov** [comment]
What do you have in the container's logs?

**Comment by readingdan** [comment]
Sorry I have given up on this and I am using Apache as this is less restrictive.
