### ISSUE TITLE
nginx reports: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by blu15** [wodby/drupal-nginx#34]
nginx complains when uploading a 14mb file. Is there a way to increase this value?

**Comment by csandanov** [comment]
Are you it's nginx? By default `NGINX_CLIENT_MAX_BODY_SIZE` set to `32m` (https://github.com/wodby/nginx#environment-variables)

**Comment by blu15** [comment]
Great, that worked! Thanks!
