### ISSUE TITLE
Compatibility with Statistics module

### ISSUE THREAD

**Issue by proteo** [wodby/drupal-nginx#36]
Hi. When using cached pages in Drupal, one can configure the Statistics module (D7) to update its counter using an Ajax call to the file:

`/modules/statistics/statistics.php`

Right now, this functionality is broken when using drupal-nginx because trying to access the file always throws an 404 error, I suspect due to these lines in the drupal.conf file:

```
location ~* ^.+\.php$ {
    return 404;
}
```

**Comment by csandanov** [comment]
Yes, we have an endpoint for D8's statistics but missed it for D7. Now added (see referenced commit).

**Comment by proteo** [comment]
Thanks!
