### ISSUE TITLE
Update.php broken in D8

### ISSUE THREAD

**Issue by rubach** [wodby/drupal-nginx#6]
There appears to be an issue with drupal8.conf. In a D8 instance, browsing to <host>/update.php, and clicking on the "Continue" button gives a 404. I found a nginx conf file that supports D8 update.php at https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/

**Comment by pprishchepa** [comment]
Hi @rubach,

Thank you for the notice. I've fixed the bug in the bab98d3d05767306446556094462722653716254 commit.

**Comment by rubach** [comment]
That fixed it. Thanks a bunch @PavelPrischepa!
