### ISSUE TITLE
Too strict nginx location rules

### ISSUE THREAD

**Issue by spleshka** [wodby/drupal-nginx#7]
Hi guys, 

First of all thanks for all your hard work on docker4drupal, it's really great. Our team tries it out with a very positive outcome.

One thing I'd like to mention here which makes local development a bit annoying is too strict configuration of nginx location. For example, if I put a custom php file in the root, then I can't access via web. The same applies to text files, etc. 

I do understand that probably you consider this image as ready for both development  & production. However, development process is quite unpredictable, and you never know if the next project you get will include custom files which has to be accessed or not. So I propose to consider several options for implementation:
* Do not restrict access to non drupal (module|inc|install|etc) files. It's the first time I see such a strict restriction in nginx
* Introduce a new setting for nginx image to make location restriction more strict (as is right now) or less strict
* Introduce opportunity to include custom nginx configs on top of pre-defined nginx config.

I know we could always inherit an image from yours and build on top, but it's much easier to include this small amend right in the main image. I'm sure lots of developers faced or will face the same issue, so why don't we make this image better together :)

Cheers,
Spleshka.

**Comment by pprishchepa** [comment]
Thank you for the feedback. The d4d config is based on https://github.com/perusio/drupal-with-nginx. It's secure and fairly well-known, so we took it as a basis.

Yes, there was some issues about too strict Nginx locations and we'll do something to make it more convenient for developers.

The following items look great. We'll implement it.

> - Do not restrict access to non drupal (module|inc|install|etc) files. It's the first time I see such a strict restriction in nginx
> - Introduce a new setting for nginx image to make location restriction more strict (as is right now) or less strict
> - Introduce opportunity to include custom nginx configs on top of pre-defined nginx config.

**Comment by spleshka** [comment]
That's awesome, thanks. Look forward. Let me know if I can help.

**Comment by csandanov** [comment]
We've added a few options to make it less strict, for example `NGINX_ALLOW_XML_ENDPOINTS`, you can add new locations via `NGINX_SERVER_EXTRA_CONF_FILEPATH` or completely rewrite it with `NGINX_CONF_INCLUDE`. 

With that being said, I still think strict rules are good especially if there's a limited known set of endpoints. As an alternative, we now have https://github.com/wodby/drupal-apache which is a pure freedom.
